### ISSUE TITLE
Build Error: library not found '-LFMDB'

### ISSUE THREAD

**Issue by conky2** [cbess/CBSearchKit#3]
I am getting this error when trying to build.

ld: warning: directory not found for option '-LFMDB'
ld: library not found for -lFMDB
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cbess** [comment]
I need more context. Got a screenshot or more log output?

**Comment by conky2** [comment]
![screen shot 2017-01-18 at 4 59 01 pm](https://cloud.githubusercontent.com/assets/25021281/22084851/a88b5c1e-dd9f-11e6-9be6-cb9154b6eb11.png)

**Comment by cbess** [comment]
Thanks for the screenshot, make sure you use `pod update/install` if you try to build the project

**Comment by cbess** [comment]
Also, check to make sure you open the workspace afterwards, not the project.
